### ISSUE TITLE
Loss of sounds.

### ISSUE THREAD

**Issue by WadeHusky** [VadimBoev/FlappyBird#11]
https://github.com/user-attachments/assets/a8fda141-3e5b-4530-9fed-a2bdbef122c1

After playing for a while, the sound disappeared. I don't know why he disappeared...

**Comment by VadimBoev** [comment]
пиздец

**Comment by ramjm** [comment]
> пиздец

Да брат, соглашусь

**Comment by ramjm** [comment]
https://github.com/user-attachments/assets/64175167-a991-4e2d-9af7-108a24c2079f

at 0:20 seconds the sound disappears.

**Comment by VadimBoev** [comment]
This has been fixed
