### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by vkensou** [VadimBoev/FlappyBird#13]
when I use ndk 25, it complain:
```
ld: error: ./obj/local/armeabi-v7a/objs-debug/flappybird/android_native_app_glue.o: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM18.0.1' Reader: 'LLVM 14.0.7git')
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

add `-opaque-pointers` after LOCAL_LDFLAGS in Android.mk fix it.

**Comment by VadimBoev** [comment]
At the moment, the project uses r27 (27.1.12297006). Please try the new version. New edits have been made here https://github.com/VadimBoev/FlappyBird/commit/0d25fbce0bbdd59889ef59f899fb459c50486e91
