### ISSUE TITLE
compile errors (Termux)

### ISSUE THREAD

**Issue by ramjm** [VadimBoev/FlappyBird#18]
Errors appear when compiling in Termux. You need to add the following header lines to the files.
Please, fix it!

upng.c
```c
#include <stdlib.h>
#include <string.h>
```

game.c
```c
#include <string.h>
```

texture.c
```c
#include <math.h>
```

utils.c
```c
#include <time.h>
```

**Comment by VadimBoev** [comment]
Thanks, added as a fix in https://github.com/VadimBoev/FlappyBird/commit/0d25fbce0bbdd59889ef59f899fb459c50486e91
