### ISSUE TITLE
Game does not work properly if installed from .apk file

### ISSUE THREAD

**Issue by karkakol** [VadimBoev/FlappyBird#22]
After tapping start button, bird does not die. Bird can hit pipe, fall through the ground and game still continues.

**Comment by VadimBoev** [comment]
Can I have more data? Video, phone model, screen frequency, and more.

**Comment by karkakol** [comment]
Phone information: Samsung s22+, Android 14, 120/60 hz.


https://github.com/user-attachments/assets/5cb09c9e-088b-4ed6-87db-3ea6bdddf77a

**Comment by VadimBoev** [comment]
There must have been some kind of mistake. I will close this issue. If the situation is not resolved after the update, create a new question
