### ISSUE TITLE
Miscellaneous tips 

### ISSUE THREAD

**Issue by An-anonymous-coder** [VadimBoev/FlappyBird#27]
1. Open up discussions for this project.
2. Consider abandoning the "under 100 KB" idea. The reason this project became so popular is because it is the only Flappy Bird clone designed for modern devices that sticks closely to the original app. Consider making that your focus, or else you will end up hurting the project by trying to keep it under 100 KB. 
3. Make sure to keep using GitHub releases with prebuilt APK files, since lots of users like to install apps via Obtainium.
4. Keep a close eye to make sure your app can work without "Allow background usage", with hardened memory allocator, with memory tagging, without native code debugging, without WebView JIT, without DLC via memory, and without DLC via storage. This should keep your app clean and respectful on devices. 
5. Change the app icon to conform to the Pixel Launcher standards. 
6. Make APK signing key hashes easily accessible, to help users verify APK files easier

**Comment by VadimBoev** [comment]
1. done
2. I can't give up on this idea, just because it's because of this idea that this repository appeared.
3. Good
4. Good
5. No. This will increase the size APK.
6. Okay, I'll do it.
