### ISSUE TITLE
Setting it up using Android studio

### ISSUE THREAD

**Issue by AbhiAndroidManiac** [VadimBoev/FlappyBird#37]
Is it possible to setup and run this code base on android studio or only vs code ide can be used for this project setpup

**Comment by VadimBoev** [comment]
Yes, you can set this up for Android Studio. You will need to create a project with only a native library, without java code (or with java code, depending on your requirements)

**Comment by AbhiAndroidManiac** [comment]
So basically NDK has to be prechecked for this. While importing it from the version control. Just curious about this approach of coding and utilization of the c++ for the android OS APKS which can be handy for many other features and challeges that are being restricted right now.
