### ISSUE TITLE
Landscape orientation issues

### ISSUE THREAD

**Issue by SRC267** [VadimBoev/FlappyBird#5]
There are currently two issues with using this app in landscape mode on my device (Xperia 1 IV (21:9 screen ratio) {Android 14}

1: when you open the app normally then rotate the phone to landscape it looks like this: ![Screenshot_20240923-003851.png](https://github.com/user-attachments/assets/99f2f5b5-78c4-4a04-b81a-3f066ec8c393)

2: When I start the app whilst the phone is already in landscape mode, the app looks stretched, as seen here: ![Screenshot_20240923-003900.png](https://github.com/user-attachments/assets/d2b7cbe6-a0d7-422c-9189-cc09778225ab)

I personally use the app normally in vertical mode, I just wanted to point out this and hopefully it looks more polished in either orientation.

**Comment by VadimBoev** [comment]
The game is designed only for vertical mode. But the problem is clear, I'll fix it.
