### ISSUE TITLE
Version number issue with Obtanium

### ISSUE THREAD

**Issue by SRC267** [VadimBoev/FlappyBird#6]
I added the repo to the Obtanium app, the app notifies you of updates to apps on GitHub. After updating to v1.1, Obtanium still thinks I'm on version 1.0: ![Screenshot_20240923-010701.png](https://github.com/user-attachments/assets/e436bd2b-889f-46ae-bed7-3cb66b54dee5)

Not sure if this is an issue on your end of with Obtanium. FWIW - all my other apps with it don't have this issue.

**Comment by VadimBoev** [comment]
Heh, yeah. I forgot to change the version in AndroidManifest

**Comment by VadimBoev** [comment]
Check out the new release
https://github.com/VadimBoev/FlappyBird/releases/tag/v1.2

**Comment by SRC267** [comment]
Nice it worked, however 1.6 installed and still showing as 1.5 in obtanium.
