### ISSUE TITLE
Support ultrawide screens

### ISSUE THREAD

**Issue by SRC267** [VadimBoev/FlappyBird#7]
So I noticed that the game on my Xperia IV phone looked too stretched, it's a very tall phone (21:9) {1644x3840} to make sure I wasn't tripping I tried the app on an old regular phone with a 16:9 screen (OnePlusOne) and it's scales much better for that old phone. See screenshots

1: My Xperia: ![Screenshot_20240923-111209.png](https://github.com/user-attachments/assets/dae2b943-0d09-47a9-b734-86f21e7eb04c)
2: My OPO: ![Screenshot_20240923-111115_FlappyBird.png](https://github.com/user-attachments/assets/3da9df9b-29db-4c33-ba38-0ec217b971be)

As you can see, it looks ugly and also a side note, the status bar is still visible at the top and the navigation bar is shown at the bottom for the Xperia. That's the gesture navigation bar, OPO doesn't have it, only physical keys. Plus, the volume keys don't work in-game.

**Comment by SRC267** [comment]
> Oh, I can't promise 21:9 support.

That's fine. To be honest, the new model of Xperia's have scrapped 21:9 support in favour of the 19.5:9 (1080x2340) ratio going forward, which is still tall but more manageable. I guess when I upgrade I will likely get that screen aspect since I usually go for Sony phones. Who knows I may get 16:9 you never know.

**Comment by VadimBoev** [comment]
Unfortunately, there will be no support for 21:9. There were no plans for this. I close your question
