### ISSUE TITLE
Input lags

### ISSUE THREAD

**Issue by VadimBoev** [VadimBoev/FlappyBird#8]
I just tested it, speed seems fine, but some inputs get ignored:

https://github.com/user-attachments/assets/7518d536-aa15-41f0-9379-65e8fe3c4296

_Originally posted by @overflowy in https://github.com/VadimBoev/FlappyBird/issues/1#issuecomment-2368641909_

**Comment by MizterSweven** [comment]
Pixel 9 Pro: big problems with input lag. It's missing a lot of inputs. It's unplayable in this state.

**Comment by MizterSweven** [comment]
https://github.com/user-attachments/assets/d60f31d3-6a3c-4cce-8e77-87ccb7d8106c

A short video of the problem. In this case it was missing 2 inputs at the start of the game.

**Comment by depleur** [comment]
Pixel 7, same issue here.

**Comment by ramjm** [comment]
Huawei nova 10 pro
+

**Comment by SRC267** [comment]
Looks like 1.6 now fixed this issue

**Comment by depleur** [comment]
> Looks like 1.6 now fixed this issue 

I doubt it, just tried it again and faced a couple of missed touches.

**Comment by MizterSweven** [comment]
Not fixed for me. It's better, but still misses inputs some times.

**Comment by Vazgen005** [comment]
Same on Pixel 8 Pro

**Comment by erovira** [comment]
Experienced this in versión 1.6 on a Pixel 6 Pro.

**Comment by DK013** [comment]
same for me in Galaxy S24 Ultra with version 1.6

**Comment by VadimBoev** [comment]
Yes, version 1.6 has brought new improvements, it is reported that there is a lower probability of 'input lags', but this does not negate the fact that it exists. At the moment, I have no idea yet what could be wrong. But, I'm still trying to figure it out and find a solution. Thanks for checking this out.

**Comment by chris-t-jansen** [comment]
v1.6 seems to fix the input lag issue on my Samsung Galaxy S22 Ultra.

**Comment by SRC267** [comment]
It definitely has improved, but it does have the occasional lag which is game breaking.

**Comment by chris-t-jansen** [comment]
This might be better under the closed issue #1, but the game still seems to be affected by refresh rate in v1.6. Attached is a screen capture of me playing the game normally, and then turning on a setting that throttles the refresh rate and playing again, where you can see the game run somewhat slower.

https://github.com/user-attachments/assets/3643a812-a375-4914-be81-8afa8ec13564

**Comment by MizterSweven** [comment]
Do you find any differences with Missing Inputs between the 2 game speeds?

**Comment by SRC267** [comment]
What I've noticed is that on 120hz every tap makes the game micro stutter. When I disable the high refresh rate and start a new game, there's no stuttering at every tap. The missing taps are still present in both screen refresh options.

**Comment by chris-t-jansen** [comment]
Not the most scientific process, but I was roughly able to set my refresh rate to 120hz, 60hz, and 48hz. 60hz seemed to run the best, with no dropped inputs that I noticed. 120hz felt like the second best, with an occasional dropped input over a couple minutes of play. 48hz was the worst for me, and regularly dropped inputs.

**Comment by JMPesce** [comment]
Same here. Error was definitely not resolved, pity.

**Comment by VadimBoev** [comment]
There has been repeated testing, now it is reported that the situation has improved and there is no problem. Please check the latest release targeting this issue: https://github.com/VadimBoev/FlappyBird/releases/tag/v1.7

**Comment by chris-t-jansen** [comment]
As near as I can tell so far, this version totally fixes the dropped input problem for me. It still runs slightly slower at lower refresh rates, but I'm not seeing any input issues or dropped inputs!

**Comment by MizterSweven** [comment]
Still Missing inputs for me on Pixel 9 pro. It's a bit better but not fixed for me

**Comment by swmarks** [comment]
1.7 is significantly better in terms of touch responsiveness. There are still micro freezes that seem to be timed around when the score updates and the corresponding sound effect plays, but I think I'm now able to play to my ability level on this game, which admittedly was always fairly average, only to the low triple digits.

**Comment by VadimBoev** [comment]
Yes, there may be freezes due to the sounds. I'll think about it

> Still Missing inputs for me on Pixel 9 pro. It's a bit better but not fixed for me

How much Hz is the screen?

**Comment by MizterSweven** [comment]
It's 120 Hz.

**Comment by VadimBoev** [comment]
> 1.7 is significantly better in terms of touch responsiveness. There are still micro freezes that seem to be timed around when the score updates and the corresponding sound effect plays, but I think I'm now able to play to my ability level on this game, which admittedly was always fairly average, only to the low triple digits.

Yes, it's really because of the sounds. I'll think about it

**Comment by VadimBoev** [comment]
> It's 120 Hz.

Please try reinstalling the game completely. And make sure that the game is version 1.7 (17)

**Comment by MizterSweven** [comment]
Reinstalling worked. No lags this time. Great

**Comment by VadimBoev** [comment]
I am seeing significant improvements. Apparently, the problem has been fixed definitively. Closing the issue

**Comment by SRC267** [comment]
60hz the game runs perfectly fine. When I change to 120hz, every tap produces a micro stutter.

**Comment by VadimBoev** [comment]
> 60hz the game runs perfectly fine. When I change to 120hz, every tap produces a micro stutter.

it probably has something to do with playing sounds, but it will be tested

**Comment by Vazgen005** [comment]
Good job!

**Comment by SRC267** [comment]
> > 60hz the game runs perfectly fine. When I change to 120hz, every tap produces a micro stutter.
> 
> it probably has something to do with playing sounds, but it will be tested

Looks like this bug has returned in v1.9, both 60hz / 120hz are affected. I reinstalled the app after a long while, so it's definitely something software related. I'm on android 14. Same device.

**Comment by VadimBoev** [comment]
> > > 60hz the game runs perfectly fine. When I change to 120hz, every tap produces a micro stutter.
> > 
> > 
> > it probably has something to do with playing sounds, but it will be tested
> 
> Looks like this bug has returned in v1.9, both 60hz / 120hz are affected. I reinstalled the app after a long while, so it's definitely something software related. I'm on android 14. Same device.

I forgot to check it, I'll take a look, sorry :)

**Comment by SRC267** [comment]
> I forgot to check it, I'll take a look, sorry :)

Updated just now, and the big still persists. Both 60hz/120hz modes.

**Comment by VadimBoev** [comment]
> > I forgot to check it, I'll take a look, sorry :)
> 
> Updated just now, and the big still persists. Both 60hz/120hz modes.

this is strange

**Comment by SRC267** [comment]
> this is strange

Yes, I think it's actually gotten a little worse than v1.9 > (1.9.1) has more jitter.
